smirik_propel_admin:
    templates:
        form:
            edit:   'SmirikPropelAdminBundle:Admin/Form:edit.html.twig'
            new:    'SmirikPropelAdminBundle:Admin/Form:new.html.twig'
            fields: 'SmirikPropelAdminBundle:Admin/Form:fields.html.twig'
        list:
            mass_actions: 'SmirikPropelAdminBundle:Admin/List:mass_actions.html.twig'
            paginate : 'SmirikPropelAdminBundle:Admin/List:paginate.html.twig'
            single_actions: 'SmirikPropelAdminBundle:Admin/List:single_actions.html.twig'
            table_filters: 'SmirikPropelAdminBundle:Admin/List:table_filters.html.twig'
            table_header : 'SmirikPropelAdminBundle:Admin/List:table_header.html.twig'
        index : 'SmirikPropelAdminBundle:Admin:index.html.twig'
        index_content : 'SmirikPropelAdminBundle:Admin:index_content.html.twig'
        row : 'SmirikPropelAdminBundle:Admin:row.html.twig'